language: csharp
solution: game.sln
git:
  depth: false

addons:
  sonarcloud:
    organization: "presque-fini"
    token:
      secure: "KjVQS8qGh0XKzAiKVpU5dD6LEWKkUxjWjB8sR7eIBtXxWivWAZHsf0nVfekGHDVxM517yzSSehzBzh/uIAqrYwwKkHqqddlbG+0Ro31vn3Ox9/RXKixRq2fWDenfoVyq1zNkXHD/3aFreZtD+DStSxggU6zPdIiu7kmsrZs8UgqWim65On03os/6ncz9hGdfWJQsgKDEvxuqax5DF7FsMskPt5nSqS4UhjWL3ktPzctMdhuCEJYQeQ9qa+yHca31FWQ3X74rJp/QQq+aSJhDRylomtZ+OjtOdJuSJiaiIXpvpsNCwDmF5BY98XHjWx2kpvymrdgWTUCR4EHy5j9tF2bfrmh5fxbMZe/fNfwci1NvXSbkCJe6WV0rWI84Qrl4eWsjBZ5M+j87apW4jP8KLm8/eyl4wlKp38s8JQiUPm/3lTUGouUpleLjfTlQyYERBMteQekO6y+WEDO08LFourxqpfSpAArO0JsF14nzAHxO9pA8x0jFuKWZa7Niu2u7yYTHYHJqgrXDa6DMXpgKwgvvvI5H0vSd6oP6beZymnAFYgWGCwlIQ24K3eUuRprMkQazj9Q/glM3/l+Ra+7UGif6NCRbyWRTlMQBmVKg3hOXO95H7BoeCz9yiACdu09K3ikeR+wODt/MLQZfWmdApdAdibdZioISX6a//z5OLg8="

before_install:
  - git clone https://github.com/prime31/Nez.git ../nez
  - wget https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/monogame-sdk.run
  - chmod +x monogame-sdk.run
  - yes | sudo ./monogame-sdk.run
  - wget https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.9.0.17385/sonar-scanner-msbuild-4.9.0.17385-net46.zip
  - unzip ./sonar-scanner-msbuild-4.9.0.17385-net46.zip -d scanner/
  - mkdir .sonarqube
  - cp -fv SonarQube.Analysis.xml .sonarqube/
  - chmod +x ./scanner/sonar-scanner-4.3.0.2102/bin/sonar-scanner

jobs:
  include:
    - script:
        - mono ./scanner/SonarScanner.MSBuild.exe begin -k:"presque-fini_presque-game" -o:"presque-fini" -d:sonar.login="a1422381008c23a74af7aa6288a7d4a76a381075" -d:sonar.projectBaseDir="/home/travis/build/presque-fini/presque-game/"
        - msbuild game.csproj
        - mono ./scanner/SonarScanner.MSBuild.exe end -d:sonar.login="a1422381008c23a74af7aa6288a7d4a76a381075"
    - script:
        - msbuild game.csproj -property:Configuration=Debug

before_deploy:
  - datetime=`date +%F`
  - zip -r release.$datetime.zip ./bin/DesktopGL/AnyCPU/Debug/
  - ls -al

deploy:
  provider: releases
  token:
    secure: "HwIJyAC9wuUXgjXwpPXCEgmXa8fb07NKDdhN16LY9ct1ZG3BSvsET/hSwe+9la5f2GxdGLm0785CYYw4aD9UejiuFCGQ2xqFMc5NUSnNVDJVVHDJv/Xw6J6lEbF9Ot918pHxjaBFW6Kz49Y5jyGmdKBgsszIZAcSOBYmz9iOmmw/yqslyt+YS5/i0BwQ1ShkY/8PSZ7wXwAE9o+aMNfZHdJfyqiomimQUE/BR2KyAkWITgwhoCAndQ/q/tzJ2FGtBU7Ch/d/+5c/yegKyPMFMOp0JaMqtmL7FRjz9BPxuKnmjbleJKDQ5JLYC0hy69ZlfnaXXRZMNaW3u5iknJbm5AlkaGHO9lIU19KZjUyxPPJeMO3vFJGbmontyF+m0Ev+Cx4wjryQLhgtVjjQnrP4ZanMkDaAsZ7TP2by4lXdpDrB7TQ4Ru/4ga13PG4Lqv1bzugkEJCqSrv0qKuhx2jr4ogKSJKSyCcoKURun5TArm02AQnaFT8EtHu9jIj3W2IaljSGXhDlH/KAgjt/Mb1Egj0WHq6QE3rtNO3EJooOg6WC5BiuxxfnodfyITCvgAjpt5gAqTGSNjtwFtmh/sPyk0Q7Geq+I8+vhZ0NNRj6ailNG7s/Lv95ZDVmEpyK0EY6W7aFtmVjaiW/80HepRJGB8sk1onl1h2xd9bRvUcH/bY="
  file: release.*.zip
  draft: true
  skip_cleanup: true
